services:
  - type: web
    name: nutritech-rpi
    runtime: python
    rootDir: backend

    buildCommand: |
      pip install -r requirements.txt
      cd ../frontend/nutritech-dashboard
      npm install
      npm run build
      mkdir -p ../../backend/frontend
      cp -r dist ../../backend/frontend/

    startCommand: gunicorn "app:create_app()"